# Generated by Django 4.1.2 on 2022-10-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oj", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="compilermodel",
            name="fail",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="compilermodel",
            name="success",
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
    ]
